sudo: false
dist: xenial
language: python
matrix:
    fast_finish: true
blocklist:
    - *-pdf
env:
    global:
        - THEANO_FLAGS=floatX=float64,compute_test_value=off
cache:
  directories:
  - "$HOME/.cache/pip"
jobs:
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'

install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install --upgrade setuptools
    - travis_retry pip install --upgrade numpy pybind11
    - travis_retry pip install --upgrade -r requirements-dev.txt
    - travis_retry python setup.py develop

script:
    - py.test -v -s src/exoplanet

after_success:
    - coveralls
