name: autoexoplanet
channels:
  - astropy
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_0
  - astropy=3.2.1=py37h7b6447c_0
  - astroquery=0.3.9=py_1000
  - atomicwrites=1.2.1=py37_0
  - attrs=18.2.0=py37h28b3542_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.7.1=py37_1
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_6
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - cffi=1.11.5=py37he75722e_1
  - chardet=3.0.4=py37_1
  - cmarkgfm=0.4.2=py37h7b6447c_0
  - cryptography=2.4.2=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.0=py37_0
  - docutils=0.14=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.17.1=py37_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_6
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_6
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - html5lib=1.0.1=py37_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.2=py37_0
  - jeepney=0.4=py37_0
  - jinja2=2.10=py37_0
  - joblib=0.12.5=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - jupyterlab=0.35.3=py37_0
  - jupyterlab_server=0.2.0=py37_0
  - keyring=17.1.1=py37_0
  - kiwisolver=1.0.1=py37hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_0
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markupsafe=1.1.0=py37h7b6447c_0
  - matplotlib=3.0.2=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.1=144
  - mkl-service=1.1.2=py37he904b0f_5
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - more-itertools=5.0.0=py37_0
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.4=py37_0
  - numpy=1.15.4=py37h7e9f1db_0
  - numpy-base=1.15.4=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_3
  - pandas=0.24.0=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - pkginfo=1.5.0.1=py37_0
  - pluggy=0.8.1=py37_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - psutil=5.4.8=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py=1.7.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pygpu=0.7.6=py37h035aef0_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.3.1=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.6.8=py37_0
  - pytest=4.1.1=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.2.0=py37_0
  - pytest-openfiles=0.3.2=py37_0
  - pytest-remotedata=0.3.1=py37_0
  - python=3.7.2=h0371630_0
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.9=py37_0
  - pyzmq=17.1.2=py37h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py37_0
  - readline=7.0=h7b6447c_5
  - readme_renderer=24.0=py37_0
  - requests=2.21.0=py37_0
  - requests-toolbelt=0.8.0=py37_0
  - scipy=1.2.0=py37h7c811a0_0
  - secretstorage=3.1.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - soupsieve=1.7.1=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py37h7b6447c_0
  - tqdm=4.29.1=py_0
  - traitlets=4.3.2=py37_0
  - twine=1.12.1=py37_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - arviz==0.4.1
    - autograd==1.3
    - bs4==0.0.1
    - cftime==1.0.3.4
    - corner==2.0.1
    - coverage==4.5.3
    - lightkurve==1.2.0
    - mako==1.0.7
    - netcdf4==1.5.1.2
    - oktopus==0.1.2
    - pymc3==3.7
    - pytest-cov==2.6.1
    - rebound==3.10.1
    - rebound-pymc3==0.0.2
    - theano==1.0.4
    - uncertainties==3.1.2
    - xarray==0.12.3
prefix: /mnt/home/dforeman/miniconda3/envs/autoexoplanet

